---

- name: install knot resolver packages
  ansible.builtin.package:
    name: "{{ knot_resolver_packages }}"
    state: present

- name: openrc
  when:
    - ansible_service_mgr | lower == 'openrc'
  block:
    - name: create kres-cache-gc init script
      ansible.builtin.template:
        src: init/openrc/init.d/kres-cache-gc.j2
        dest: /etc/init.d/kres-cache-gc
        mode: 0755

    - name: create kresd  init script
      ansible.builtin.template:
        src: init/openrc/init.d/kresd.j2
        dest: /etc/init.d/kresd
        mode: 0755

- name: update trusted-key
  kdig:
    root_dns: "k.root-servers.net"
    key_signing_key: 257
    trust_keyfile: /etc/trusted-key.key
  notify:
    - restart kresd

...
