---

- name: prepare
  ansible.builtin.include_tasks: prepare.yaml

- name: repositories
  ansible.builtin.include_tasks: repositories.yaml

- name: install
  ansible.builtin.include_tasks: install.yaml

- name: configure
  ansible.builtin.include_tasks: configure.yaml

- name: service
  ansible.builtin.include_tasks: service.yaml

...
