---

- name: include OS specific configuration
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20.04 / centos-8 / oraclelinux-8
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yaml"
        # eg. archlinux-systemd / archlinux-openrc
        - "{{ ansible_distribution | lower }}-{{ ansible_service_mgr | lower }}.yaml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_distribution | lower }}.yaml"
        # eg. redhat / debian / archlinux
        - "{{ ansible_os_family | lower }}.yaml"
        # artixlinux
        - "{{ ansible_os_family | lower | replace(' ', '') }}.yaml"
        - default.yaml
      skip: true

- name: update package cache
  package:
    update_cache: true

- name: install dedendency
  package:
    name: "{{ knot_resolver_dependencies }}"
    state: present
  when:
    - knot_resolver_dependencies is defined
    - knot_resolver_dependencies | count > 0

- name: merge cache configuration between defaults and custom
  set_fact:
    knot_resolver_cache: "{{ knot_resolver_defaults_cache |
      combine( knot_resolver_cache, recursive=True ) }}"

- name: merge log configuration between defaults and custom
  set_fact:
    knot_resolver_log: "{{ knot_resolver_defaults_log |
      combine( knot_resolver_log, recursive=True ) }}"

- name: get latest system information
  setup:

...
