---

- name: include OS specific configuration
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20.04 / centos-8 / oraclelinux-8
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yaml"
        # eg. archlinux-systemd / archlinux-openrc
        - "{{ ansible_distribution | lower }}-{{ ansible_service_mgr | lower }}.yaml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_distribution | lower }}.yaml"
        # eg. redhat / debian / archlinux
        - "{{ ansible_os_family | lower }}.yaml"
        # artixlinux
        - "{{ ansible_os_family | lower | replace(' ', '') }}.yaml"
        - default.yaml
      skip: true

- name: update package cache
  ansible.builtin.package:
    update_cache: true

- name: install dedendency
  ansible.builtin.package:
    name: "{{ knot_resolver_dependencies }}"
    state: present
  when:
    - knot_resolver_dependencies is defined
    - knot_resolver_dependencies | count > 0

- name: user and group handling
  when:
    - knot_resolver_owner != "root"
  block:
    - name: create kresd group
      ansible.builtin.group:
        name: "{{ knot_resolver_group }}"
        state: present
        system: true

    - name: create kresd user
      ansible.builtin.user:
        name: "{{ knot_resolver_owner }}"
        groups: "{{ knot_resolver_group }}"
        append: true
        shell: /usr/sbin/nologin
        system: true
        createhome: false
        home: /nonexistent

- name: merge knot_resolver configuration between defaults and custom
  ansible.builtin.set_fact:
    knot_resolver_cache: "{{ knot_resolver_defaults_cache | combine(knot_resolver_cache, recursive=True) }}"
    knot_resolver_log: "{{ knot_resolver_defaults_log | combine(knot_resolver_log, recursive=True) }}"
    knot_resolver_prometheus: "{{ knot_resolver_defaults_prometheus | combine(knot_resolver_prometheus, recursive=True) }}"
    knot_resolver_predict: "{{ knot_resolver_defaults_predict | combine(knot_resolver_predict, recursive=True) }}"

- name: get latest system information
  ansible.builtin.setup:

...
