---

- name: start and enable Knot Resolver service
  with_sequence: "count={{ knot_resolver_systemd_instances }}"
  service:
    name: "kresd@{{ item }}.service"
    state: started
    enabled: true

...
