---

- name: start and enable Knot Resolver service (systemd)
  with_sequence: "count={{ knot_resolver_systemd_instances }}"
  service:
    name: "kresd@{{ item }}.service"
    state: started
    enabled: true
  when:
    - ansible_service_mgr | lower == 'systemd'

- name: start and enable Knot Resolver service (openrc)
  service:
    name: kresd
    state: started
    enabled: true
  when:
    - ansible_service_mgr | lower == 'openrc'

...
