---

- name: restart knot resolver (systemd)
  with_sequence: "count={{ knot_resolver_systemd_instances }}"
  listen: "restart knot resolver"
  service:
    name: "kresd@{{ item }}.service"
    state: restarted
  when:
    - ansible_service_mgr | lower == 'systemd'

- name: restart knot resolver (openrc)
  listen: "restart knot resolver"
  service:
    name: kresd
    state: restarted
  when:
    - ansible_service_mgr | lower == 'openrc'

- name: restart kres-cache-gc (openrc)
  listen: "restart kres-cache-gc"
  service:
    name: kres-cache-gc
    state: restarted
  when:
    - ansible_service_mgr | lower == 'openrc'

...
