---
- name: converge
  hosts: all
  any_errors_fatal: false

  environment:
    NETRC: ''

  roles:
    #- role: pacman
    #  when:
    #    - ansible_distribution | lower == 'archlinux' or
    #      ansible_os_family | lower == 'artix linux'
    - role: ansible-knot-resolver

