---

knot_resolver_listener:
  - name: localhost
    #interfaces:
    #  - eth0
    ips:
      - '127.0.0.1'
    port: 53
  #  options:
  #    tls: true

knot_resolver_internal_domain:
  - domains:
      - 'molecule.lan'
      - 'matrix.lan'
      - '0.172.in-addr.arpa'
    policy:
      stub: '127.0.0.1@5353'

knot_resolver_cachesize: 100

knot_resolver_views:
  - pass:
      - '127.0.0.0/8'
      - '192.168.0.0/24'
  - drop:
      - '0.0.0.0/0'

...
