---

knot_resolver_listener:
  - name: localhost
    #interfaces:
    #  - eth0
    ips:
      - '127.0.0.1'
    port: 53
  #  options:
  #    tls: true
  - name: tls
    ips:
      - '127.0.0.1'
    port: 853
    options:
      kind: tls
  - name: webmgmt
    ips:
      - '127.0.0.1'
    port: 8453
    options:
      kind: webmgmt

knot_resolver_internal_domain:
  - domains:
      - 'molecule.lan'
      - '0.172.in-addr.arpa'
    policy:
      stub: '127.0.0.1@5353'

knot_resolver_cache:
  # directory: /var/cache/knot-resolver
  max_ttl: 1200
  size: 100

knot_resolver_views:
  - pass:
      - '127.0.0.0/8'
      - '192.168.0.0/24'
  - drop:
      - '0.0.0.0/0'

...
